[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
krak = "6YuaHDGkiwMhSj8y5rkznTPohHJpeU96LnCq3U7dRkz5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
